# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84fe44c3e2ebec8c5a2dde6215fc4803ebc9f0d5da42151b19ba1dd08c8c5a241b6e20a06a3d6842419d9db0d46c1ea79db7e4fe7665298e0f2b79e41f6390a2

test:
  secret_key_base: 22a753cc58126fe71be278a3ab981594cfb8af2f329ca3c25f591b64090167b2f4ff0111aedb499cd3fa354a70a0dcdfc5607c5ca0d9f58292e8e633f1c0e2a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
